language: python

os: linux

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -q -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME/miniconda3"
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda update --quiet --yes conda

  - conda env create -f environment.yml
  - source activate pygrf
  - python setup.py develop

script:
  - pytest pygrf/tests

notifications:
  email: never
